server:
  port: 8086
  contextPath: /kyc 

#PostgreSQL    
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/db_sema_kyc
        username: postgres
        password: root
        driver-class-name: org.postgresql.Driver

# Hibernate
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: create-drop
            naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
        database-platform: org.hibernate.dialect.PostgreSQLDialect

#======================================================
##IPRS Configuration
#======================================================
iprs:
    endPoint: http://10.1.1.5:9004/IPRSServerWCF
    userName: SEMAMOBILE
    password: n12Qu64
    matchThreshold: 50